name: 02 - Test Commit Trigger
on: push
jobs:
  run-push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This runs on a push"

      - name: This step is skipped
        if: false
        run: echo "I should be skipped"
