name: 04 - Test Upstream Dependent
on:
  push:
  workflow_dispatch:
jobs:
  run-upstream:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "I am upstream, running..."
          sleep 10
