name: Observer

on:
  push:
  pull_request:
  workflow_dispatch:
  # Automatically triggers the Observer if specific workflows are fired manually (workflow_dispatch)
  # You must maintain this list with the names of any workflows you want to monitor manually.
  workflow_run:
    workflows: 
      - "01 - Test Manual Trigger"
      - "03 - Test Long Running"
      - "04 - Test Upstream Dependent"
    types:
      - requested

concurrency:
  group: observer-${{ github.sha }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  telemetry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Telemetry Observer Action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          initial_delay: '60'
          max_timeout: '3600'
          poll_interval: '15'
          ignored_workflows: 'Observer,CodeQL,Dependabot'
          # api_url: 'https://api.yourdomain.com/telemetry'
          # api_key: ${{ secrets.TELEMETRY_API_KEY }}
          generate_svg_report: 'true'

        
      - name: Upload Telemetry Data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: telemetry-test-jsons
          path: test_jsons/
          
      - name: Upload SVG Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: workflow-svg-report
          path: workflow_status.svg
